### ISSUE TITLE
add a way to open the idea file in read-only without committing

### ISSUE THREAD

**Issue by mchataigner** [simeg/eureka#24] opened 2018-08-23 13:42 UTC
Currently, the only way to interact with the readme.md file is to launch eureka that will open the editor and the commit changes and push to upstream.

It would be interesting to be able to open in read-only this file with a PAGER (like less, more, most…) to read the content. It will avoid the commit/push after closing the file.

**Comment by simeg** [comment] 2018-08-27 16:11
I agree, it's way up on my todo list. Like why write down ideas if you can't look at them afterwards - it doesn't make sense. Using a pager is a good idea, what do you think about using `less` as default?

Later we can implement a way of just outputting to `stdout` so you can pipe the content to any process you want, using a flag perhaps.

**Comment by simeg** [comment] 2018-11-04 12:53
Duplicate of #7.

**Closed as completed by simeg** 2018-11-04 12:53 UTC
